name: Pull Requests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run lint
      - run: npm run test
